### ISSUE TITLE
ActiveAdminRole without Devise

### ISSUE THREAD

**Issue by lgm1213** [yhirano55/active_admin_role#2]
Tried to install without Devise, but the generators gave an error. Is it possible to use this gem without Devise?

**Comment by yhirano55** [comment]
Thanks for the question. Let's paste error logs?

**Comment by yhirano55** [comment]
In conclusion, this gem doesn't depend on Devise. But it need to `User` or `AdminUser` model, because controller must know who current user is.

**Comment by lgm1213** [comment]
```
rails generate active_admin_role:install --skip-users
Running via Spring preloader in process 17462
   identical  config/initializers/active_admin_role.rb
    generate  active_admin:install AdminUser
Running via Spring preloader in process 17469
      invoke  devise
/home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/lib/generators/active_admin/devise/devise_generator.rb:22:in `rescue in install_devise': To use devise you need to specify it in your Gemfile. If you don't want to use devise, run the generator with --skip-users. (ActiveAdmin::GeneratorError)
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/lib/generators/active_admin/devise/devise_generator.rb:19:in `install_devise'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/shell.rb:68:in `with_padding'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:133:in `_invoke_from_option_users'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/generators.rb:269:in `invoke'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/generate/generate_command.rb:24:in `perform'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/luis/Desktop/LetsLeaseIt/bin/rails:9:in `<top (required)>'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/luis/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
      insert  app/models/admin_user.rb
The file /home/luis/Desktop/LetsLeaseIt/app/models/admin_user.rb does not appear to exist

```

**Comment by yhirano55** [comment]
Thanks. If you don't need to use devise, you have to generate User or AdminUser model before install. If User or AdminUser model is, it will skip the step `activeadmin:install`.

https://github.com/yhirano55/active_admin_role/blob/master/lib/generators/active_admin_role/install_generator.rb#L22-L25

**Comment by lgm1213** [comment]
I had a User model when I ran rails generate active_admin_role:install --skip-users.

**Comment by yhirano55** [comment]
Ah I see. You might resolve to execute `rails g active_admin_role:install --model User`. Could you try it?

**Comment by lgm1213** [comment]
It worked! Thank you so much!
